version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mne_user
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: mne
    ports:
      - "5432:5432"
